// Generates app/theme/colors.css from one seed color using the official
// Material color algorithm. Run with `pnpm theme` after changing the seed.
//
// The seed must not read as a Taiwanese party color (see docs/design-system.md).
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  argbFromHex,
  Contrast,
  type DynamicScheme,
  Hct,
  hexFromArgb,
  lstarFromArgb,
  MaterialDynamicColors,
  SchemeTonalSpot,
} from "@material/material-color-utilities";

const SEED = "#6750A4";
const STANDARD = 0;
const HIGH = 1;

const colors = new MaterialDynamicColors().allColors.filter(
  (c) => !c.name.endsWith("_palette_key_color"),
);

function scheme(isDark: boolean, contrast: number): DynamicScheme {
  return new SchemeTonalSpot(Hct.fromInt(argbFromHex(SEED)), isDark, contrast);
}

function declarations(s: DynamicScheme, indent: string): string {
  return colors
    .map(
      (c) =>
        `${indent}--md-sys-color-${c.name.replaceAll("_", "-")}: ${hexFromArgb(c.getArgb(s))};`,
    )
    .join("\n");
}

// Every role pair that carries text must reach 4.5:1 in every scheme.
const TEXT_PAIRS: [string, string][] = [
  ["on_primary", "primary"],
  ["on_primary_container", "primary_container"],
  ["on_secondary", "secondary"],
  ["on_secondary_container", "secondary_container"],
  ["on_tertiary", "tertiary"],
  ["on_tertiary_container", "tertiary_container"],
  ["on_error", "error"],
  ["on_error_container", "error_container"],
  ["on_surface", "surface"],
  ["on_surface", "surface_container_lowest"],
  ["on_surface", "surface_container_highest"],
  ["on_surface_variant", "surface"],
  ["on_surface_variant", "surface_container_highest"],
  ["primary", "surface"],
  ["inverse_on_surface", "inverse_surface"],
];

function assertContrast(label: string, s: DynamicScheme) {
  const byName = new Map(colors.map((c) => [c.name, c]));
  for (const [fg, bg] of TEXT_PAIRS) {
    const f = byName.get(fg);
    const b = byName.get(bg);
    if (!f || !b) throw new Error(`unknown color role in pair ${fg}/${bg}`);
    const ratio = Contrast.ratioOfTones(lstarFromArgb(f.getArgb(s)), lstarFromArgb(b.getArgb(s)));
    if (ratio < 4.5) {
      throw new Error(`${label}: ${fg} on ${bg} is ${ratio.toFixed(2)}:1, below 4.5:1`);
    }
  }
}

const schemes = {
  light: scheme(false, STANDARD),
  dark: scheme(true, STANDARD),
  lightHigh: scheme(false, HIGH),
  darkHigh: scheme(true, HIGH),
};
for (const [label, s] of Object.entries(schemes)) assertContrast(label, s);

// data-theme on <html> is the reader's explicit choice (from a cookie, so the
// server renders it); without it the OS preference decides.
const css = `/* Generated by scripts/generate-theme.ts from seed ${SEED}. Do not edit. */

:root {
  color-scheme: light;
${declarations(schemes.light, "  ")}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${declarations(schemes.dark, "    ")}
  }
}

:root[data-theme="dark"] {
  color-scheme: dark;
${declarations(schemes.dark, "  ")}
}

@media (prefers-contrast: more) {
  :root {
${declarations(schemes.lightHigh, "    ")}
  }

  :root[data-theme="dark"] {
${declarations(schemes.darkHigh, "    ")}
  }
}

@media (prefers-contrast: more) and (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${declarations(schemes.darkHigh, "    ")}
  }
}
`;

const out = fileURLToPath(new URL("../app/theme/colors.css", import.meta.url));
writeFileSync(out, css);
console.log(`wrote ${out}`);
