/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events, most recently updated first */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One event with its timeline and coverage */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/outlets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The outlets the site covers */
        get: operations["listOutlets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                code: string;
                message: string;
            };
        };
        Outlet: {
            /** Format: int64 */
            id: number;
            slug: string;
            name: string;
            domain?: string;
        };
        EventSummary: {
            /** Format: int64 */
            id: number;
            title: string;
            /** Format: date-time */
            firstSeenAt: string;
            /** Format: date-time */
            updatedAt: string;
            articleCount: number;
            outletCount: number;
            /** @description The most recent timeline step; empty when the event has none. */
            latestDevelopment: string;
        };
        EventsPage: {
            events: components["schemas"]["EventSummary"][];
            nextCursor: string | null;
        };
        EventDetail: {
            /** Format: int64 */
            id: number;
            title: string;
            /** Format: date-time */
            firstSeenAt: string;
            /** Format: date-time */
            updatedAt: string;
            articleCount: number;
            outletCount: number;
            /** @description Developments in the event, oldest first. */
            timeline: components["schemas"]["TimelineStep"][];
            /** @description Coverage, newest first. Wire reprints are folded under their original. */
            articles: components["schemas"]["Article"][];
        };
        TimelineStep: {
            /**
             * Format: int64
             * @description The first article that reported the development.
             */
            articleId: number;
            development: string;
            /**
             * Format: date
             * @description Calendar date in Asia/Taipei.
             */
            happenedOn: string;
            dateIsApproximate: boolean;
            /** @description Outlets that reported the development, ordered by publish time. */
            reports: components["schemas"]["StepReport"][];
        };
        StepReport: {
            /**
             * Format: int64
             * @description The article card to link to; for a wire reprint, the original.
             */
            articleId: number;
            outlet: components["schemas"]["Outlet"];
            /** Format: date-time */
            publishedAt: string;
        };
        Article: {
            /** Format: int64 */
            id: number;
            outlet: components["schemas"]["Outlet"];
            /** @description The original headline, unchanged. */
            headline: string;
            /** Format: uri */
            url: string;
            /** Format: date-time */
            publishedAt: string;
            /** @description Empty for a headline-only article. */
            summary: string;
            /** @description True for outlets that don't allow AI use of their content. Only the headline and link are shown; the article is never summarized. */
            headlineOnly: boolean;
            reprints: components["schemas"]["Reprint"][];
        };
        Reprint: {
            outlet: components["schemas"]["Outlet"];
            /** Format: uri */
            url: string;
            /** Format: date-time */
            publishedAt: string;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listEvents: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous page's nextCursor. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsPage"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The event */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listOutlets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Outlets ordered by name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        outlets: components["schemas"]["Outlet"][];
                    };
                };
            };
        };
    };
}
