// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const copyArticleEntitiesToEvent = `-- name: CopyArticleEntitiesToEvent :exec
INSERT INTO event_entities (event_id, entity_id)
SELECT $1, ae.entity_id FROM article_entities ae WHERE ae.article_id = $2
ON CONFLICT DO NOTHING
`

type CopyArticleEntitiesToEventParams struct {
	EventID   int64
	ArticleID int64
}

func (q *Queries) CopyArticleEntitiesToEvent(ctx context.Context, arg CopyArticleEntitiesToEventParams) error {
	_, err := q.db.Exec(ctx, copyArticleEntitiesToEvent, arg.EventID, arg.ArticleID)
	return err
}

const copyEventEntities = `-- name: CopyEventEntities :exec
INSERT INTO event_entities (event_id, entity_id)
SELECT $1, ee.entity_id FROM event_entities ee WHERE ee.event_id = $2
ON CONFLICT DO NOTHING
`

type CopyEventEntitiesParams struct {
	ToEventID   int64
	FromEventID int64
}

func (q *Queries) CopyEventEntities(ctx context.Context, arg CopyEventEntitiesParams) error {
	_, err := q.db.Exec(ctx, copyEventEntities, arg.ToEventID, arg.FromEventID)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const deleteEventIfEmpty = `-- name: DeleteEventIfEmpty :exec
DELETE FROM events e
WHERE e.id = $1 AND NOT EXISTS (SELECT 1 FROM articles a WHERE a.event_id = e.id)
`

func (q *Queries) DeleteEventIfEmpty(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteEventIfEmpty, id)
	return err
}

const getArticleForMove = `-- name: GetArticleForMove :one
SELECT id, event_id, step_article_id, development, reprint_of_id
FROM articles
WHERE id = $1
FOR UPDATE
`

type GetArticleForMoveRow struct {
	ID            int64
	EventID       pgtype.Int8
	StepArticleID pgtype.Int8
	Development   string
	ReprintOfID   pgtype.Int8
}

func (q *Queries) GetArticleForMove(ctx context.Context, id int64) (GetArticleForMoveRow, error) {
	row := q.db.QueryRow(ctx, getArticleForMove, id)
	var i GetArticleForMoveRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.StepArticleID,
		&i.Development,
		&i.ReprintOfID,
	)
	return i, err
}

const listLinkDecisions = `-- name: ListLinkDecisions :many

SELECT
    a.id, a.headline, a.published_at, a.link_confidence,
    o.name AS outlet_name,
    e.id AS event_id, e.title AS event_title
FROM articles a
JOIN outlets o ON o.id = a.outlet_id
JOIN events e ON e.id = a.event_id
WHERE a.link_confidence IS NOT NULL
  AND a.link_confidence <= $1
ORDER BY a.link_confidence, a.id DESC
LIMIT $2
`

type ListLinkDecisionsParams struct {
	MaxConfidence pgtype.Float4
	MaxResults    int32
}

type ListLinkDecisionsRow struct {
	ID             int64
	Headline       string
	PublishedAt    time.Time
	LinkConfidence pgtype.Float4
	OutletName     string
	EventID        int64
	EventTitle     string
}

// Queries used by the admin tool to review and correct event linking.
// Linked articles, least confident first, for review.
func (q *Queries) ListLinkDecisions(ctx context.Context, arg ListLinkDecisionsParams) ([]ListLinkDecisionsRow, error) {
	rows, err := q.db.Query(ctx, listLinkDecisions, arg.MaxConfidence, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinkDecisionsRow{}
	for rows.Next() {
		var i ListLinkDecisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Headline,
			&i.PublishedAt,
			&i.LinkConfidence,
			&i.OutletName,
			&i.EventID,
			&i.EventTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepFollowers = `-- name: ListStepFollowers :many
SELECT id, development
FROM articles
WHERE step_article_id = $1
  AND id <> $1
  AND event_id = $2
ORDER BY published_at, id
`

type ListStepFollowersParams struct {
	StepArticleID pgtype.Int8
	EventID       pgtype.Int8
}

type ListStepFollowersRow struct {
	ID          int64
	Development string
}

// Articles in an event that attach to the given step, other than the step
// article itself, earliest first.
func (q *Queries) ListStepFollowers(ctx context.Context, arg ListStepFollowersParams) ([]ListStepFollowersRow, error) {
	rows, err := q.db.Query(ctx, listStepFollowers, arg.StepArticleID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStepFollowersRow{}
	for rows.Next() {
		var i ListStepFollowersRow
		if err := rows.Scan(&i.ID, &i.Development); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEvent = `-- name: LockEvent :one
SELECT id, first_seen_at FROM events WHERE id = $1 FOR UPDATE
`

type LockEventRow struct {
	ID          int64
	FirstSeenAt time.Time
}

func (q *Queries) LockEvent(ctx context.Context, id int64) (LockEventRow, error) {
	row := q.db.QueryRow(ctx, lockEvent, id)
	var i LockEventRow
	err := row.Scan(&i.ID, &i.FirstSeenAt)
	return i, err
}

const moveArticle = `-- name: MoveArticle :exec
UPDATE articles
SET event_id = $2, step_article_id = $3, link_confidence = 1, manual_link = true
WHERE id = $1
`

type MoveArticleParams struct {
	ID            int64
	EventID       pgtype.Int8
	StepArticleID pgtype.Int8
}

// An admin's decision is certain, so the confidence becomes 1.
func (q *Queries) MoveArticle(ctx context.Context, arg MoveArticleParams) error {
	_, err := q.db.Exec(ctx, moveArticle, arg.ID, arg.EventID, arg.StepArticleID)
	return err
}

const moveEventArticles = `-- name: MoveEventArticles :exec
UPDATE articles SET event_id = $1, manual_link=true WHERE event_id = $2
`

type MoveEventArticlesParams struct {
	ToEventID   pgtype.Int8
	FromEventID pgtype.Int8
}

func (q *Queries) MoveEventArticles(ctx context.Context, arg MoveEventArticlesParams) error {
	_, err := q.db.Exec(ctx, moveEventArticles, arg.ToEventID, arg.FromEventID)
	return err
}

const repointStep = `-- name: RepointStep :exec
UPDATE articles
SET step_article_id = $1
WHERE step_article_id = $2 AND event_id = $3
`

type RepointStepParams struct {
	NewStepID pgtype.Int8
	OldStepID pgtype.Int8
	EventID   pgtype.Int8
}

func (q *Queries) RepointStep(ctx context.Context, arg RepointStepParams) error {
	_, err := q.db.Exec(ctx, repointStep, arg.NewStepID, arg.OldStepID, arg.EventID)
	return err
}

const searchEventsByTitle = `-- name: SearchEventsByTitle :many
SELECT e.id, e.title, e.updated_at,
    (SELECT count(*) FROM articles a WHERE a.event_id = e.id)::bigint AS article_count
FROM events e
WHERE e.title ILIKE '%' || $1::text || '%'
   OR e.id::text = $1::text
ORDER BY e.updated_at DESC
LIMIT $2
`

type SearchEventsByTitleParams struct {
	Query      string
	MaxResults int32
}

type SearchEventsByTitleRow struct {
	ID           int64
	Title        string
	UpdatedAt    time.Time
	ArticleCount int64
}

// Finds the target event for a merge or a move. Matches the title loosely, or
// an exact id typed as a number.
func (q *Queries) SearchEventsByTitle(ctx context.Context, arg SearchEventsByTitleParams) ([]SearchEventsByTitleRow, error) {
	rows, err := q.db.Query(ctx, searchEventsByTitle, arg.Query, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEventsByTitleRow{}
	for rows.Next() {
		var i SearchEventsByTitleRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.UpdatedAt,
			&i.ArticleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEventFirstSeen = `-- name: SetEventFirstSeen :exec
UPDATE events SET first_seen_at = LEAST(first_seen_at, $1) WHERE id = $2
`

type SetEventFirstSeenParams struct {
	FirstSeenAt time.Time
	ID          int64
}

func (q *Queries) SetEventFirstSeen(ctx context.Context, arg SetEventFirstSeenParams) error {
	_, err := q.db.Exec(ctx, setEventFirstSeen, arg.FirstSeenAt, arg.ID)
	return err
}
