// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (
    outlet_id, event_id, url, headline, body, published_at, first_seen_at,
    content_hash, reprint_of_id, development, happened_on, date_is_approximate
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id
`

type CreateArticleParams struct {
	OutletID          int64
	EventID           pgtype.Int8
	Url               string
	Headline          string
	Body              string
	PublishedAt       time.Time
	FirstSeenAt       time.Time
	ContentHash       string
	ReprintOfID       pgtype.Int8
	Development       string
	HappenedOn        pgtype.Date
	DateIsApproximate bool
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (int64, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.OutletID,
		arg.EventID,
		arg.Url,
		arg.Headline,
		arg.Body,
		arg.PublishedAt,
		arg.FirstSeenAt,
		arg.ContentHash,
		arg.ReprintOfID,
		arg.Development,
		arg.HappenedOn,
		arg.DateIsApproximate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listEventArticles = `-- name: ListEventArticles :many
SELECT
    a.id,
    a.url,
    a.headline,
    a.image_url,
    a.published_at,
    a.first_seen_at,
    a.reprint_of_id,
    a.development,
    a.happened_on,
    a.date_is_approximate,
    a.step_article_id,
    o.id AS outlet_id,
    o.slug AS outlet_slug,
    o.name AS outlet_name,
    (a.body = '')::boolean AS headline_only,
    COALESCE(s.text, '')::text AS summary
FROM articles a
JOIN outlets o ON o.id = a.outlet_id
LEFT JOIN summaries s ON s.article_id = a.id
WHERE a.event_id = $1::bigint
ORDER BY a.published_at DESC, a.id DESC
`

type ListEventArticlesRow struct {
	ID                int64
	Url               string
	Headline          string
	ImageUrl          string
	PublishedAt       time.Time
	FirstSeenAt       time.Time
	ReprintOfID       pgtype.Int8
	Development       string
	HappenedOn        pgtype.Date
	DateIsApproximate bool
	StepArticleID     pgtype.Int8
	OutletID          int64
	OutletSlug        string
	OutletName        string
	HeadlineOnly      bool
	Summary           string
}

// Every article of an event with its outlet and summary. The body is
// deliberately not selected: article text is never served.
func (q *Queries) ListEventArticles(ctx context.Context, eventID int64) ([]ListEventArticlesRow, error) {
	rows, err := q.db.Query(ctx, listEventArticles, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventArticlesRow{}
	for rows.Next() {
		var i ListEventArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Headline,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FirstSeenAt,
			&i.ReprintOfID,
			&i.Development,
			&i.HappenedOn,
			&i.DateIsApproximate,
			&i.StepArticleID,
			&i.OutletID,
			&i.OutletSlug,
			&i.OutletName,
			&i.HeadlineOnly,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setArticleStep = `-- name: SetArticleStep :exec
UPDATE articles SET step_article_id = $2 WHERE id = $1
`

type SetArticleStepParams struct {
	ID            int64
	StepArticleID pgtype.Int8
}

func (q *Queries) SetArticleStep(ctx context.Context, arg SetArticleStepParams) error {
	_, err := q.db.Exec(ctx, setArticleStep, arg.ID, arg.StepArticleID)
	return err
}

const upsertSummary = `-- name: UpsertSummary :exec
INSERT INTO summaries (article_id, text, recaps, model, prompt_version)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (article_id) DO UPDATE
SET text = EXCLUDED.text,
    recaps = EXCLUDED.recaps,
    model = EXCLUDED.model,
    prompt_version = EXCLUDED.prompt_version,
    created_at = now()
`

type UpsertSummaryParams struct {
	ArticleID     int64
	Text          string
	Recaps        []string
	Model         string
	PromptVersion string
}

func (q *Queries) UpsertSummary(ctx context.Context, arg UpsertSummaryParams) error {
	_, err := q.db.Exec(ctx, upsertSummary,
		arg.ArticleID,
		arg.Text,
		arg.Recaps,
		arg.Model,
		arg.PromptVersion,
	)
	return err
}
