// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
	"time"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (title, first_seen_at, updated_at)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateEventParams struct {
	Title       string
	FirstSeenAt time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, createEvent, arg.Title, arg.FirstSeenAt, arg.UpdatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getEvent = `-- name: GetEvent :one
SELECT
    e.id,
    e.title,
    e.summary,
    e.first_seen_at,
    e.updated_at,
    (SELECT count(*) FROM articles a WHERE a.event_id = e.id)::bigint AS article_count,
    (SELECT count(DISTINCT a.outlet_id) FROM articles a WHERE a.event_id = e.id)::bigint AS outlet_count
FROM events e
WHERE e.id = $1
`

type GetEventRow struct {
	ID           int64
	Title        string
	Summary      string
	FirstSeenAt  time.Time
	UpdatedAt    time.Time
	ArticleCount int64
	OutletCount  int64
}

func (q *Queries) GetEvent(ctx context.Context, id int64) (GetEventRow, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i GetEventRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.FirstSeenAt,
		&i.UpdatedAt,
		&i.ArticleCount,
		&i.OutletCount,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT
    e.id,
    e.title,
    e.first_seen_at,
    e.updated_at,
    (SELECT count(*) FROM articles a WHERE a.event_id = e.id)::bigint AS article_count,
    (SELECT count(DISTINCT a.outlet_id) FROM articles a WHERE a.event_id = e.id)::bigint AS outlet_count,
    COALESCE((
        SELECT a.development
        FROM articles a
        WHERE a.event_id = e.id AND a.step_article_id = a.id
        ORDER BY COALESCE(a.happened_on, a.published_at::date) DESC, a.published_at DESC
        LIMIT 1
    ), '')::text AS latest_development
FROM events e
WHERE (e.updated_at, e.id) < ($1::timestamptz, $2::bigint)
  AND EXISTS (SELECT 1 FROM articles a WHERE a.event_id = e.id)
ORDER BY e.updated_at DESC, e.id DESC
LIMIT $3
`

type ListEventsParams struct {
	CursorUpdatedAt time.Time
	CursorID        int64
	PageSize        int32
}

type ListEventsRow struct {
	ID                int64
	Title             string
	FirstSeenAt       time.Time
	UpdatedAt         time.Time
	ArticleCount      int64
	OutletCount       int64
	LatestDevelopment string
}

// Keyset pagination, most recently updated first. For the first page pass a
// far-future cursor_updated_at and the maximum bigint as cursor_id.
func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.CursorUpdatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FirstSeenAt,
			&i.UpdatedAt,
			&i.ArticleCount,
			&i.OutletCount,
			&i.LatestDevelopment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsSharingEntities = `-- name: ListEventsSharingEntities :many
SELECT
    ee.event_id AS id,
    count(*)::bigint AS shared
FROM event_entities ee
WHERE ee.entity_id = ANY($1::bigint[])
GROUP BY ee.event_id
ORDER BY shared DESC, ee.event_id DESC
LIMIT $2
`

type ListEventsSharingEntitiesParams struct {
	EntityIds  []int64
	MaxResults int32
}

type ListEventsSharingEntitiesRow struct {
	ID     int64
	Shared int64
}

// Candidate events that involve any of the given entities, most shared first.
// Shared names alone never merge events; this only nominates candidates.
func (q *Queries) ListEventsSharingEntities(ctx context.Context, arg ListEventsSharingEntitiesParams) ([]ListEventsSharingEntitiesRow, error) {
	rows, err := q.db.Query(ctx, listEventsSharingEntities, arg.EntityIds, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsSharingEntitiesRow{}
	for rows.Next() {
		var i ListEventsSharingEntitiesRow
		if err := rows.Scan(&i.ID, &i.Shared); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEventCandidates = `-- name: SearchEventCandidates :many
SELECT
    e.id,
    e.title,
    ts_rank(e.search, q.query) AS rank
FROM events e,
    (SELECT replace(plainto_tsquery('english', $1::text)::text, '&', '|')::tsquery AS query) q
WHERE e.search @@ q.query
ORDER BY rank DESC, e.updated_at DESC
LIMIT $2
`

type SearchEventCandidatesParams struct {
	SearchText string
	MaxResults int32
}

type SearchEventCandidatesRow struct {
	ID    int64
	Title string
	Rank  float32
}

// Candidate events for a new article, by full-text match of the article's
// development and recap lines against event titles and timelines. Terms are
// OR-ed (plainto_tsquery would AND them, which is far too strict for a
// paraphrased follow-up) and ranked, so a partial match still surfaces.
// There is deliberately no time limit: a follow-up may come months later.
func (q *Queries) SearchEventCandidates(ctx context.Context, arg SearchEventCandidatesParams) ([]SearchEventCandidatesRow, error) {
	rows, err := q.db.Query(ctx, searchEventCandidates, arg.SearchText, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEventCandidatesRow{}
	for rows.Next() {
		var i SearchEventCandidatesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Rank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEventTimelineText = `-- name: SetEventTimelineText :exec
UPDATE events
SET timeline_text = $2
WHERE id = $1
`

type SetEventTimelineTextParams struct {
	ID           int64
	TimelineText string
}

// Called whenever an event gains a step, so the search index stays current.
func (q *Queries) SetEventTimelineText(ctx context.Context, arg SetEventTimelineTextParams) error {
	_, err := q.db.Exec(ctx, setEventTimelineText, arg.ID, arg.TimelineText)
	return err
}
