// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingestion.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const admitAnalysis = `-- name: AdmitAnalysis :exec
INSERT INTO ai_admissions(article_id,outlet_id,admitted_on) VALUES($1,$2,$3)
`

type AdmitAnalysisParams struct {
	ArticleID  int64
	OutletID   int64
	AdmittedOn pgtype.Date
}

func (q *Queries) AdmitAnalysis(ctx context.Context, arg AdmitAnalysisParams) error {
	_, err := q.db.Exec(ctx, admitAnalysis, arg.ArticleID, arg.OutletID, arg.AdmittedOn)
	return err
}

const countDailyAdmissions = `-- name: CountDailyAdmissions :one
SELECT count(*) FROM ai_admissions WHERE admitted_on=$1
`

func (q *Queries) CountDailyAdmissions(ctx context.Context, admittedOn pgtype.Date) (int64, error) {
	row := q.db.QueryRow(ctx, countDailyAdmissions, admittedOn)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const crawlFailures = `-- name: CrawlFailures :many
SELECT o.slug,c.result,c.http_status,c.error,count(*)::bigint AS articles
FROM crawl_urls c JOIN outlets o ON o.id=c.outlet_id
WHERE c.error<>'' AND ($1::text='' OR o.slug=$1)
GROUP BY o.slug,c.result,c.http_status,c.error ORDER BY o.slug,articles DESC
`

type CrawlFailuresRow struct {
	Slug       string
	Result     string
	HttpStatus int32
	Error      string
	Articles   int64
}

func (q *Queries) CrawlFailures(ctx context.Context, slug string) ([]CrawlFailuresRow, error) {
	rows, err := q.db.Query(ctx, crawlFailures, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CrawlFailuresRow{}
	for rows.Next() {
		var i CrawlFailuresRow
		if err := rows.Scan(
			&i.Slug,
			&i.Result,
			&i.HttpStatus,
			&i.Error,
			&i.Articles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const crawlStatus = `-- name: CrawlStatus :many
SELECT o.slug,
 count(c.url)::bigint AS discovered,
 count(c.url) FILTER(WHERE c.result='success')::bigint AS fetched,
 count(c.url) FILTER(WHERE c.result NOT IN ('pending','success'))::bigint AS failed,
 count(c.url) FILTER(WHERE c.result='success' AND c.eligible AND a.reprint_of_id IS NULL AND s.article_id IS NULL)::bigint AS awaiting_analysis,
 min(c.first_seen_at) FILTER(WHERE c.result='success' AND c.eligible AND a.reprint_of_id IS NULL AND s.article_id IS NULL) AS oldest_waiting,
 max(c.fetched_at) AS last_success
FROM outlets o LEFT JOIN crawl_urls c ON c.outlet_id=o.id
LEFT JOIN articles a ON a.id=c.article_id LEFT JOIN summaries s ON s.article_id=a.id
WHERE $1::text='' OR o.slug=$1
GROUP BY o.id,o.slug ORDER BY o.slug
`

type CrawlStatusRow struct {
	Slug             string
	Discovered       int64
	Fetched          int64
	Failed           int64
	AwaitingAnalysis int64
	OldestWaiting    interface{}
	LastSuccess      interface{}
}

func (q *Queries) CrawlStatus(ctx context.Context, slug string) ([]CrawlStatusRow, error) {
	rows, err := q.db.Query(ctx, crawlStatus, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CrawlStatusRow{}
	for rows.Next() {
		var i CrawlStatusRow
		if err := rows.Scan(
			&i.Slug,
			&i.Discovered,
			&i.Fetched,
			&i.Failed,
			&i.AwaitingAnalysis,
			&i.OldestWaiting,
			&i.LastSuccess,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const discoverURL = `-- name: DiscoverURL :exec
INSERT INTO crawl_urls(url,outlet_id,source,headline,image_url,category,scope_reason,eligible,published_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)
ON CONFLICT(url) DO UPDATE SET
 headline=CASE WHEN crawl_urls.headline='' THEN EXCLUDED.headline ELSE crawl_urls.headline END,
 image_url=CASE WHEN crawl_urls.image_url='' THEN EXCLUDED.image_url ELSE crawl_urls.image_url END,
 category=CASE WHEN crawl_urls.category='' THEN EXCLUDED.category ELSE crawl_urls.category END,
 eligible=CASE WHEN crawl_urls.category='' THEN EXCLUDED.eligible ELSE crawl_urls.eligible END,
 scope_reason=CASE WHEN crawl_urls.category='' THEN EXCLUDED.scope_reason ELSE crawl_urls.scope_reason END,
 published_at=COALESCE(crawl_urls.published_at,EXCLUDED.published_at),last_seen_at=now()
`

type DiscoverURLParams struct {
	Url         string
	OutletID    int64
	Source      string
	Headline    string
	ImageUrl    string
	Category    string
	ScopeReason string
	Eligible    bool
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) DiscoverURL(ctx context.Context, arg DiscoverURLParams) error {
	_, err := q.db.Exec(ctx, discoverURL,
		arg.Url,
		arg.OutletID,
		arg.Source,
		arg.Headline,
		arg.ImageUrl,
		arg.Category,
		arg.ScopeReason,
		arg.Eligible,
		arg.PublishedAt,
	)
	return err
}

const getCrawlURL = `-- name: GetCrawlURL :one
SELECT url, outlet_id, source, headline, image_url, category, scope_reason, eligible, published_at, first_seen_at, last_seen_at, result, http_status, error, extractor, body_length, fetched_at, next_attempt_at, article_id FROM crawl_urls WHERE url=$1
`

func (q *Queries) GetCrawlURL(ctx context.Context, url string) (CrawlUrl, error) {
	row := q.db.QueryRow(ctx, getCrawlURL, url)
	var i CrawlUrl
	err := row.Scan(
		&i.Url,
		&i.OutletID,
		&i.Source,
		&i.Headline,
		&i.ImageUrl,
		&i.Category,
		&i.ScopeReason,
		&i.Eligible,
		&i.PublishedAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Result,
		&i.HttpStatus,
		&i.Error,
		&i.Extractor,
		&i.BodyLength,
		&i.FetchedAt,
		&i.NextAttemptAt,
		&i.ArticleID,
	)
	return i, err
}

const getSourceProgress = `-- name: GetSourceProgress :one
SELECT outlet_id, source, mode, since_at, progress, error, updated_at FROM crawl_sources WHERE outlet_id=$1 AND source=$2 AND mode=$3
`

type GetSourceProgressParams struct {
	OutletID int64
	Source   string
	Mode     string
}

func (q *Queries) GetSourceProgress(ctx context.Context, arg GetSourceProgressParams) (CrawlSource, error) {
	row := q.db.QueryRow(ctx, getSourceProgress, arg.OutletID, arg.Source, arg.Mode)
	var i CrawlSource
	err := row.Scan(
		&i.OutletID,
		&i.Source,
		&i.Mode,
		&i.SinceAt,
		&i.Progress,
		&i.Error,
		&i.UpdatedAt,
	)
	return i, err
}

const hasAdmission = `-- name: HasAdmission :one
SELECT EXISTS(SELECT 1 FROM ai_admissions WHERE article_id=$1)
`

func (q *Queries) HasAdmission(ctx context.Context, articleID int64) (bool, error) {
	row := q.db.QueryRow(ctx, hasAdmission, articleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFetchCandidates = `-- name: ListFetchCandidates :many
WITH candidates AS (
SELECT url,row_number() OVER(PARTITION BY outlet_id ORDER BY (article_id IS NOT NULL) DESC,first_seen_at,url) AS position FROM crawl_urls
WHERE result IN ('pending','retry') AND next_attempt_at<=now() AND eligible
AND outlet_id IN (SELECT id FROM outlets WHERE enabled)
)
SELECT c.url,c.outlet_id,c.published_at,c.image_url FROM crawl_urls c JOIN candidates d ON d.url=c.url
ORDER BY d.position,c.first_seen_at,c.url LIMIT $1 FOR UPDATE OF c SKIP LOCKED
`

type ListFetchCandidatesRow struct {
	Url         string
	OutletID    int64
	PublishedAt pgtype.Timestamptz
	ImageUrl    string
}

func (q *Queries) ListFetchCandidates(ctx context.Context, limit int32) ([]ListFetchCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listFetchCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFetchCandidatesRow{}
	for rows.Next() {
		var i ListFetchCandidatesRow
		if err := rows.Scan(
			&i.Url,
			&i.OutletID,
			&i.PublishedAt,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAnalysisReady = `-- name: MarkAnalysisReady :exec
INSERT INTO analysis_pending(article_id) VALUES($1) ON CONFLICT DO NOTHING
`

func (q *Queries) MarkAnalysisReady(ctx context.Context, articleID int64) error {
	_, err := q.db.Exec(ctx, markAnalysisReady, articleID)
	return err
}

const nextAnalysisCandidate = `-- name: NextAnalysisCandidate :one
SELECT a.id,a.outlet_id FROM analysis_pending p JOIN articles a ON a.id=p.article_id
JOIN outlets o ON o.id=a.outlet_id
WHERE o.enabled AND a.body<>'' AND a.reprint_of_id IS NULL
AND NOT EXISTS(SELECT 1 FROM summaries s WHERE s.article_id=a.id)
AND NOT EXISTS(SELECT 1 FROM ai_admissions d WHERE d.article_id=a.id)
AND NOT EXISTS(SELECT 1 FROM crawl_urls c WHERE c.article_id=a.id AND NOT c.eligible)
ORDER BY
 (SELECT count(*) FROM ai_admissions d WHERE d.outlet_id=a.outlet_id AND d.admitted_on=$1),
 (SELECT max(d.admitted_at) FROM ai_admissions d WHERE d.outlet_id=a.outlet_id) ASC NULLS FIRST,
 p.ready_at,a.id LIMIT 1
`

type NextAnalysisCandidateRow struct {
	ID       int64
	OutletID int64
}

func (q *Queries) NextAnalysisCandidate(ctx context.Context, admittedOn pgtype.Date) (NextAnalysisCandidateRow, error) {
	row := q.db.QueryRow(ctx, nextAnalysisCandidate, admittedOn)
	var i NextAnalysisCandidateRow
	err := row.Scan(&i.ID, &i.OutletID)
	return i, err
}

const recordFetchFailure = `-- name: RecordFetchFailure :exec
UPDATE crawl_urls SET result=$2,http_status=$3,error=$4,next_attempt_at=$5 WHERE url=$1
`

type RecordFetchFailureParams struct {
	Url           string
	Result        string
	HttpStatus    int32
	Error         string
	NextAttemptAt time.Time
}

func (q *Queries) RecordFetchFailure(ctx context.Context, arg RecordFetchFailureParams) error {
	_, err := q.db.Exec(ctx, recordFetchFailure,
		arg.Url,
		arg.Result,
		arg.HttpStatus,
		arg.Error,
		arg.NextAttemptAt,
	)
	return err
}

const recordFetchSuccess = `-- name: RecordFetchSuccess :exec
UPDATE crawl_urls SET result='success',http_status=200,error='',article_id=$2,
 extractor=$3,body_length=$4,fetched_at=now(),category=$5,eligible=$6,scope_reason=$7,
 published_at=COALESCE($8::timestamptz,published_at)
WHERE url=$1
`

type RecordFetchSuccessParams struct {
	Url         string
	ArticleID   pgtype.Int8
	Extractor   string
	BodyLength  int32
	Category    string
	Eligible    bool
	ScopeReason string
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) RecordFetchSuccess(ctx context.Context, arg RecordFetchSuccessParams) error {
	_, err := q.db.Exec(ctx, recordFetchSuccess,
		arg.Url,
		arg.ArticleID,
		arg.Extractor,
		arg.BodyLength,
		arg.Category,
		arg.Eligible,
		arg.ScopeReason,
		arg.PublishedAt,
	)
	return err
}

const reserveFetch = `-- name: ReserveFetch :exec
UPDATE crawl_urls SET next_attempt_at=now()+interval '30 minutes' WHERE url=$1
`

func (q *Queries) ReserveFetch(ctx context.Context, url string) error {
	_, err := q.db.Exec(ctx, reserveFetch, url)
	return err
}

const saveSourceProgress = `-- name: SaveSourceProgress :exec
INSERT INTO crawl_sources(outlet_id,source,mode,since_at,progress,error)
VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(outlet_id,source,mode)
DO UPDATE SET since_at=EXCLUDED.since_at,progress=EXCLUDED.progress,error=EXCLUDED.error,updated_at=now()
`

type SaveSourceProgressParams struct {
	OutletID int64
	Source   string
	Mode     string
	SinceAt  time.Time
	Progress []byte
	Error    string
}

func (q *Queries) SaveSourceProgress(ctx context.Context, arg SaveSourceProgressParams) error {
	_, err := q.db.Exec(ctx, saveSourceProgress,
		arg.OutletID,
		arg.Source,
		arg.Mode,
		arg.SinceAt,
		arg.Progress,
		arg.Error,
	)
	return err
}

const sourceStatus = `-- name: SourceStatus :many
SELECT o.slug,s.source,s.mode,s.progress,s.error,s.updated_at FROM crawl_sources s
JOIN outlets o ON o.id=s.outlet_id
WHERE $1::text='' OR o.slug=$1 ORDER BY o.slug,s.source,s.mode
`

type SourceStatusRow struct {
	Slug      string
	Source    string
	Mode      string
	Progress  []byte
	Error     string
	UpdatedAt time.Time
}

func (q *Queries) SourceStatus(ctx context.Context, slug string) ([]SourceStatusRow, error) {
	rows, err := q.db.Query(ctx, sourceStatus, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SourceStatusRow{}
	for rows.Next() {
		var i SourceStatusRow
		if err := rows.Scan(
			&i.Slug,
			&i.Source,
			&i.Mode,
			&i.Progress,
			&i.Error,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
