// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AiAdmission struct {
	ArticleID  int64
	OutletID   int64
	AdmittedOn pgtype.Date
	AdmittedAt time.Time
}

type AnalysisPending struct {
	ArticleID int64
	ReadyAt   time.Time
}

type Article struct {
	ID                int64
	OutletID          int64
	EventID           pgtype.Int8
	Url               string
	Headline          string
	Body              string
	PublishedAt       time.Time
	FirstSeenAt       time.Time
	ContentHash       string
	Minhash           []int32
	ReprintOfID       pgtype.Int8
	Development       string
	HappenedOn        pgtype.Date
	DateIsApproximate bool
	StepArticleID     pgtype.Int8
	LinkConfidence    pgtype.Float4
	ManualLink        bool
	ImageUrl          string
	DevelopmentZh     string
}

type ArticleEntity struct {
	ArticleID int64
	EntityID  int64
}

type CrawlSource struct {
	OutletID  int64
	Source    string
	Mode      string
	SinceAt   time.Time
	Progress  []byte
	Error     string
	UpdatedAt time.Time
}

type CrawlUrl struct {
	Url           string
	OutletID      int64
	Source        string
	Headline      string
	ImageUrl      string
	Category      string
	ScopeReason   string
	Eligible      bool
	PublishedAt   pgtype.Timestamptz
	FirstSeenAt   time.Time
	LastSeenAt    time.Time
	Result        string
	HttpStatus    int32
	Error         string
	Extractor     string
	BodyLength    int32
	FetchedAt     pgtype.Timestamptz
	NextAttemptAt time.Time
	ArticleID     pgtype.Int8
}

type Entity struct {
	ID            int64
	CanonicalName string
	Kind          string
	Aliases       []string
	SearchText    string
}

type Event struct {
	ID                   int64
	Title                string
	FirstSeenAt          time.Time
	UpdatedAt            time.Time
	TimelineText         string
	Search               interface{}
	Summary              string
	SummaryModel         string
	SummaryPromptVersion string
	TitleZh              string
	SummaryZh            string
}

type EventEntity struct {
	EventID  int64
	EntityID int64
}

type Outlet struct {
	ID           int64
	Slug         string
	Name         string
	Domain       string
	IsAggregator bool
	Enabled      bool
	CrawlConfig  []byte
	CreatedAt    time.Time
}

type Summary struct {
	ArticleID     int64
	Text          string
	Recaps        []string
	Model         string
	PromptVersion string
	CreatedAt     time.Time
	TextZh        string
}
