// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outlets.sql

package db

import (
	"context"
)

const findOutletByName = `-- name: FindOutletByName :one
SELECT id
FROM outlets
WHERE name = $1 AND NOT is_aggregator
`

// Resolves the publisher an aggregator names to one of our outlets.
func (q *Queries) FindOutletByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, findOutletByName, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOutlet = `-- name: GetOutlet :one
SELECT id, slug, name, is_aggregator, enabled, crawl_config, coverage
FROM outlets
WHERE id = $1
`

type GetOutletRow struct {
	ID           int64
	Slug         string
	Name         string
	IsAggregator bool
	Enabled      bool
	CrawlConfig  []byte
	Coverage     string
}

func (q *Queries) GetOutlet(ctx context.Context, id int64) (GetOutletRow, error) {
	row := q.db.QueryRow(ctx, getOutlet, id)
	var i GetOutletRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.IsAggregator,
		&i.Enabled,
		&i.CrawlConfig,
		&i.Coverage,
	)
	return i, err
}

const listEnabledOutlets = `-- name: ListEnabledOutlets :many
SELECT id, slug, name, is_aggregator, crawl_config
FROM outlets
WHERE enabled
ORDER BY id
`

type ListEnabledOutletsRow struct {
	ID           int64
	Slug         string
	Name         string
	IsAggregator bool
	CrawlConfig  []byte
}

func (q *Queries) ListEnabledOutlets(ctx context.Context) ([]ListEnabledOutletsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledOutlets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledOutletsRow{}
	for rows.Next() {
		var i ListEnabledOutletsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.IsAggregator,
			&i.CrawlConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicOutlets = `-- name: ListPublicOutlets :many
SELECT id, slug, name, domain
FROM outlets
WHERE NOT is_aggregator
ORDER BY name
`

type ListPublicOutletsRow struct {
	ID     int64
	Slug   string
	Name   string
	Domain string
}

func (q *Queries) ListPublicOutlets(ctx context.Context) ([]ListPublicOutletsRow, error) {
	rows, err := q.db.Query(ctx, listPublicOutlets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicOutletsRow{}
	for rows.Next() {
		var i ListPublicOutletsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Domain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOutletCrawl = `-- name: SetOutletCrawl :exec
UPDATE outlets
SET enabled = $2, crawl_config = $3
WHERE slug = $1
`

type SetOutletCrawlParams struct {
	Slug        string
	Enabled     bool
	CrawlConfig []byte
}

func (q *Queries) SetOutletCrawl(ctx context.Context, arg SetOutletCrawlParams) error {
	_, err := q.db.Exec(ctx, setOutletCrawl, arg.Slug, arg.Enabled, arg.CrawlConfig)
	return err
}

const upsertOutlet = `-- name: UpsertOutlet :one
INSERT INTO outlets (slug, name, domain, is_aggregator, enabled, crawl_config, coverage)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name,
    domain = EXCLUDED.domain,
    is_aggregator = EXCLUDED.is_aggregator,
    -- The seed only supplies crawl settings for an outlet that has none, so
    -- settings changed in the database are never overwritten by a re-seed.
    enabled = CASE WHEN outlets.crawl_config = '{}' THEN EXCLUDED.enabled ELSE outlets.enabled END,
    crawl_config = CASE WHEN outlets.crawl_config = '{}' THEN EXCLUDED.crawl_config ELSE outlets.crawl_config END,
    -- Coverage is policy, not tuning: the seed list is its source of truth.
    coverage = EXCLUDED.coverage
RETURNING id
`

type UpsertOutletParams struct {
	Slug         string
	Name         string
	Domain       string
	IsAggregator bool
	Enabled      bool
	CrawlConfig  []byte
	Coverage     string
}

func (q *Queries) UpsertOutlet(ctx context.Context, arg UpsertOutletParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertOutlet,
		arg.Slug,
		arg.Name,
		arg.Domain,
		arg.IsAggregator,
		arg.Enabled,
		arg.CrawlConfig,
		arg.Coverage,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
