// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipeline.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEntity = `-- name: CreateEntity :one
INSERT INTO entities (canonical_name, kind, aliases, search_text)
VALUES ($1, $2, $3, $4)
ON CONFLICT (canonical_name) DO UPDATE SET canonical_name = EXCLUDED.canonical_name
RETURNING id
`

type CreateEntityParams struct {
	CanonicalName string
	Kind          string
	Aliases       []string
	SearchText    string
}

func (q *Queries) CreateEntity(ctx context.Context, arg CreateEntityParams) (int64, error) {
	row := q.db.QueryRow(ctx, createEntity,
		arg.CanonicalName,
		arg.Kind,
		arg.Aliases,
		arg.SearchText,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const existingArticleURLs = `-- name: ExistingArticleURLs :many

SELECT url FROM articles WHERE url = ANY($1::text[])
`

// Queries used by the ingestion pipeline (internal/jobs, internal/link).
func (q *Queries) ExistingArticleURLs(ctx context.Context, urls []string) ([]string, error) {
	rows, err := q.db.Query(ctx, existingArticleURLs, urls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEntity = `-- name: FindEntity :one
SELECT id, canonical_name, aliases
FROM entities
WHERE kind = $1
  AND (canonical_name = $2 OR $2::text = ANY(aliases))
ORDER BY id
LIMIT 1
`

type FindEntityParams struct {
	Kind string
	Name string
}

type FindEntityRow struct {
	ID            int64
	CanonicalName string
	Aliases       []string
}

// An exact match on the canonical name or any alias, within one kind.
func (q *Queries) FindEntity(ctx context.Context, arg FindEntityParams) (FindEntityRow, error) {
	row := q.db.QueryRow(ctx, findEntity, arg.Kind, arg.Name)
	var i FindEntityRow
	err := row.Scan(&i.ID, &i.CanonicalName, &i.Aliases)
	return i, err
}

const getArticleForAnalysis = `-- name: GetArticleForAnalysis :one
SELECT a.id, a.headline, a.body, a.published_at, a.reprint_of_id, o.name AS outlet_name
FROM articles a
JOIN outlets o ON o.id = a.outlet_id
WHERE a.id = $1
`

type GetArticleForAnalysisRow struct {
	ID          int64
	Headline    string
	Body        string
	PublishedAt time.Time
	ReprintOfID pgtype.Int8
	OutletName  string
}

func (q *Queries) GetArticleForAnalysis(ctx context.Context, id int64) (GetArticleForAnalysisRow, error) {
	row := q.db.QueryRow(ctx, getArticleForAnalysis, id)
	var i GetArticleForAnalysisRow
	err := row.Scan(
		&i.ID,
		&i.Headline,
		&i.Body,
		&i.PublishedAt,
		&i.ReprintOfID,
		&i.OutletName,
	)
	return i, err
}

const getArticleForDedupe = `-- name: GetArticleForDedupe :one
SELECT id, outlet_id, minhash, published_at, reprint_of_id, manual_link
FROM articles
WHERE id = $1
`

type GetArticleForDedupeRow struct {
	ID          int64
	OutletID    int64
	Minhash     []int32
	PublishedAt time.Time
	ReprintOfID pgtype.Int8
	ManualLink  bool
}

func (q *Queries) GetArticleForDedupe(ctx context.Context, id int64) (GetArticleForDedupeRow, error) {
	row := q.db.QueryRow(ctx, getArticleForDedupe, id)
	var i GetArticleForDedupeRow
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.Minhash,
		&i.PublishedAt,
		&i.ReprintOfID,
		&i.ManualLink,
	)
	return i, err
}

const getArticleForLink = `-- name: GetArticleForLink :one
SELECT
    a.id, a.headline, a.development, a.published_at, a.first_seen_at, a.manual_link, a.step_article_id, a.event_id, a.reprint_of_id,
    COALESCE(s.text, '')::text AS summary,
    COALESCE(s.recaps, '{}')::text[] AS recaps
FROM articles a
LEFT JOIN summaries s ON s.article_id = a.id
WHERE a.id = $1
`

type GetArticleForLinkRow struct {
	ID            int64
	Headline      string
	Development   string
	PublishedAt   time.Time
	FirstSeenAt   time.Time
	ManualLink    bool
	StepArticleID pgtype.Int8
	EventID       pgtype.Int8
	ReprintOfID   pgtype.Int8
	Summary       string
	Recaps        []string
}

func (q *Queries) GetArticleForLink(ctx context.Context, id int64) (GetArticleForLinkRow, error) {
	row := q.db.QueryRow(ctx, getArticleForLink, id)
	var i GetArticleForLinkRow
	err := row.Scan(
		&i.ID,
		&i.Headline,
		&i.Development,
		&i.PublishedAt,
		&i.FirstSeenAt,
		&i.ManualLink,
		&i.StepArticleID,
		&i.EventID,
		&i.ReprintOfID,
		&i.Summary,
		&i.Recaps,
	)
	return i, err
}

const getEventForSummary = `-- name: GetEventForSummary :one
SELECT id, title, updated_at, summary_model, summary_prompt_version
FROM events
WHERE id = $1
`

type GetEventForSummaryRow struct {
	ID                   int64
	Title                string
	UpdatedAt            time.Time
	SummaryModel         string
	SummaryPromptVersion string
}

func (q *Queries) GetEventForSummary(ctx context.Context, id int64) (GetEventForSummaryRow, error) {
	row := q.db.QueryRow(ctx, getEventForSummary, id)
	var i GetEventForSummaryRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.UpdatedAt,
		&i.SummaryModel,
		&i.SummaryPromptVersion,
	)
	return i, err
}

const getEventTitles = `-- name: GetEventTitles :many
SELECT id, title FROM events WHERE id = ANY($1::bigint[])
`

type GetEventTitlesRow struct {
	ID    int64
	Title string
}

func (q *Queries) GetEventTitles(ctx context.Context, eventIds []int64) ([]GetEventTitlesRow, error) {
	rows, err := q.db.Query(ctx, getEventTitles, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventTitlesRow{}
	for rows.Next() {
		var i GetEventTitlesRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSummaryVersion = `-- name: GetSummaryVersion :one
SELECT model, prompt_version FROM summaries WHERE article_id = $1
`

type GetSummaryVersionRow struct {
	Model         string
	PromptVersion string
}

func (q *Queries) GetSummaryVersion(ctx context.Context, articleID int64) (GetSummaryVersionRow, error) {
	row := q.db.QueryRow(ctx, getSummaryVersion, articleID)
	var i GetSummaryVersionRow
	err := row.Scan(&i.Model, &i.PromptVersion)
	return i, err
}

const insertFetchedArticle = `-- name: InsertFetchedArticle :one
INSERT INTO articles (outlet_id, url, headline, image_url, body, published_at, content_hash, minhash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (url) DO UPDATE SET headline=EXCLUDED.headline,body=EXCLUDED.body,
image_url=CASE WHEN articles.image_url='' THEN EXCLUDED.image_url ELSE articles.image_url END,
published_at=EXCLUDED.published_at,content_hash=EXCLUDED.content_hash,minhash=EXCLUDED.minhash
WHERE articles.body=''
RETURNING id
`

type InsertFetchedArticleParams struct {
	OutletID    int64
	Url         string
	Headline    string
	ImageUrl    string
	Body        string
	PublishedAt time.Time
	ContentHash string
	Minhash     []int32
}

// Returns no row when the URL is already stored, which makes a retried fetch a no-op.
func (q *Queries) InsertFetchedArticle(ctx context.Context, arg InsertFetchedArticleParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertFetchedArticle,
		arg.OutletID,
		arg.Url,
		arg.Headline,
		arg.ImageUrl,
		arg.Body,
		arg.PublishedAt,
		arg.ContentHash,
		arg.Minhash,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const linkArticleEntity = `-- name: LinkArticleEntity :exec
INSERT INTO article_entities (article_id, entity_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type LinkArticleEntityParams struct {
	ArticleID int64
	EntityID  int64
}

func (q *Queries) LinkArticleEntity(ctx context.Context, arg LinkArticleEntityParams) error {
	_, err := q.db.Exec(ctx, linkArticleEntity, arg.ArticleID, arg.EntityID)
	return err
}

const linkEventEntity = `-- name: LinkEventEntity :exec
INSERT INTO event_entities (event_id, entity_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type LinkEventEntityParams struct {
	EventID  int64
	EntityID int64
}

func (q *Queries) LinkEventEntity(ctx context.Context, arg LinkEventEntityParams) error {
	_, err := q.db.Exec(ctx, linkEventEntity, arg.EventID, arg.EntityID)
	return err
}

const listArticleEntities = `-- name: ListArticleEntities :many
SELECT e.id, e.canonical_name
FROM article_entities ae
JOIN entities e ON e.id = ae.entity_id
WHERE ae.article_id = $1
ORDER BY e.id
`

type ListArticleEntitiesRow struct {
	ID            int64
	CanonicalName string
}

func (q *Queries) ListArticleEntities(ctx context.Context, articleID int64) ([]ListArticleEntitiesRow, error) {
	rows, err := q.db.Query(ctx, listArticleEntities, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticleEntitiesRow{}
	for rows.Next() {
		var i ListArticleEntitiesRow
		if err := rows.Scan(&i.ID, &i.CanonicalName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesMissingImage = `-- name: ListArticlesMissingImage :many
WITH ranked AS (
    SELECT
        a.id,
        a.url,
        a.event_id,
        e.updated_at AS event_updated_at,
        a.published_at,
        row_number() OVER (PARTITION BY a.event_id ORDER BY a.published_at DESC, a.id DESC) AS event_rank,
        EXISTS (
            SELECT 1 FROM articles image
            WHERE image.event_id = a.event_id AND image.image_url <> ''
        ) AS event_has_image
    FROM articles a
    LEFT JOIN events e ON e.id = a.event_id
    WHERE a.image_url = ''
)
SELECT id, url
FROM ranked
ORDER BY
    (event_id IS NOT NULL AND NOT event_has_image AND event_rank = 1) DESC,
    (event_id IS NOT NULL) DESC,
    event_updated_at DESC NULLS LAST,
    published_at DESC,
    id DESC
LIMIT $1
`

type ListArticlesMissingImageRow struct {
	ID  int64
	Url string
}

func (q *Queries) ListArticlesMissingImage(ctx context.Context, maxResults int32) ([]ListArticlesMissingImageRow, error) {
	rows, err := q.db.Query(ctx, listArticlesMissingImage, maxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesMissingImageRow{}
	for rows.Next() {
		var i ListArticlesMissingImageRow
		if err := rows.Scan(&i.ID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesMissingZh = `-- name: ListArticlesMissingZh :many
SELECT
    a.id,
    a.development,
    a.development_zh,
    s.text AS summary,
    s.text_zh AS summary_zh,
    COALESCE((
        SELECT array_agg(en.canonical_name ORDER BY en.id)
        FROM article_entities ae JOIN entities en ON en.id = ae.entity_id
        WHERE ae.article_id = a.id
    ), '{}')::text[] AS names
FROM articles a
JOIN summaries s ON s.article_id = a.id
WHERE (s.text_zh = '' AND s.text <> '')
   OR (a.development_zh = '' AND a.development <> '')
ORDER BY a.published_at DESC
LIMIT $1
`

type ListArticlesMissingZhRow struct {
	ID            int64
	Development   string
	DevelopmentZh string
	Summary       string
	SummaryZh     string
	Names         []string
}

// Analyzed articles whose summary or timeline line has no Chinese version yet.
func (q *Queries) ListArticlesMissingZh(ctx context.Context, maxResults int32) ([]ListArticlesMissingZhRow, error) {
	rows, err := q.db.Query(ctx, listArticlesMissingZh, maxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesMissingZhRow{}
	for rows.Next() {
		var i ListArticlesMissingZhRow
		if err := rows.Scan(
			&i.ID,
			&i.Development,
			&i.DevelopmentZh,
			&i.Summary,
			&i.SummaryZh,
			&i.Names,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventSteps = `-- name: ListEventSteps :many
SELECT a.event_id, a.id, a.development, a.happened_on, a.published_at
FROM articles a
WHERE a.event_id = ANY($1::bigint[])
  AND a.step_article_id = a.id
  AND a.development <> ''
ORDER BY a.event_id, COALESCE(a.happened_on, a.published_at::date), a.published_at
`

type ListEventStepsRow struct {
	EventID     pgtype.Int8
	ID          int64
	Development string
	HappenedOn  pgtype.Date
	PublishedAt time.Time
}

// The timeline steps of the given events, oldest first.
func (q *Queries) ListEventSteps(ctx context.Context, eventIds []int64) ([]ListEventStepsRow, error) {
	rows, err := q.db.Query(ctx, listEventSteps, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventStepsRow{}
	for rows.Next() {
		var i ListEventStepsRow
		if err := rows.Scan(
			&i.EventID,
			&i.ID,
			&i.Development,
			&i.HappenedOn,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventSummarySources = `-- name: ListEventSummarySources :many
SELECT a.development, s.text AS summary
FROM articles a
JOIN summaries s ON s.article_id = a.id
WHERE a.event_id = $1::bigint AND a.reprint_of_id IS NULL
ORDER BY a.published_at ASC, a.id ASC
`

type ListEventSummarySourcesRow struct {
	Development string
	Summary     string
}

func (q *Queries) ListEventSummarySources(ctx context.Context, eventID int64) ([]ListEventSummarySourcesRow, error) {
	rows, err := q.db.Query(ctx, listEventSummarySources, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventSummarySourcesRow{}
	for rows.Next() {
		var i ListEventSummarySourcesRow
		if err := rows.Scan(&i.Development, &i.Summary); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsMissingZh = `-- name: ListEventsMissingZh :many
SELECT
    e.id,
    e.title,
    e.title_zh,
    e.summary,
    e.summary_zh,
    COALESCE((
        SELECT array_agg(en.canonical_name ORDER BY en.id)
        FROM event_entities ee JOIN entities en ON en.id = ee.entity_id
        WHERE ee.event_id = e.id
    ), '{}')::text[] AS names
FROM events e
WHERE (e.title_zh = '' OR (e.summary <> '' AND e.summary_zh = ''))
  AND EXISTS (SELECT 1 FROM articles a WHERE a.event_id = e.id)
ORDER BY e.updated_at DESC
LIMIT $1
`

type ListEventsMissingZhRow struct {
	ID        int64
	Title     string
	TitleZh   string
	Summary   string
	SummaryZh string
	Names     []string
}

// Events still without a Chinese title, with the original-script entity names
// the translation must reuse. Only events that are shown (have articles).
func (q *Queries) ListEventsMissingZh(ctx context.Context, maxResults int32) ([]ListEventsMissingZhRow, error) {
	rows, err := q.db.Query(ctx, listEventsMissingZh, maxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsMissingZhRow{}
	for rows.Next() {
		var i ListEventsMissingZhRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleZh,
			&i.Summary,
			&i.SummaryZh,
			&i.Names,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsNeedingSummary = `-- name: ListEventsNeedingSummary :many
SELECT e.id
FROM events e
WHERE (e.summary_model <> $1 OR e.summary_prompt_version <> $2)
  AND EXISTS (
      SELECT 1 FROM articles a JOIN summaries s ON s.article_id = a.id
      WHERE a.event_id = e.id AND a.reprint_of_id IS NULL
      AND a.url NOT LIKE 'https://example.com/ground-sample/%'
  )
ORDER BY e.updated_at DESC
LIMIT $3
`

type ListEventsNeedingSummaryParams struct {
	Model         string
	PromptVersion string
	MaxResults    int32
}

func (q *Queries) ListEventsNeedingSummary(ctx context.Context, arg ListEventsNeedingSummaryParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listEventsNeedingSummary, arg.Model, arg.PromptVersion, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSignatures = `-- name: ListRecentSignatures :many
SELECT a.id, a.minhash, a.event_id
FROM articles a
WHERE a.first_seen_at >= $1
  AND a.id < $2
  AND a.reprint_of_id IS NULL
  AND cardinality(a.minhash) > 0
  AND NOT EXISTS(SELECT 1 FROM crawl_urls c WHERE c.article_id=a.id AND NOT c.eligible)
ORDER BY a.published_at, a.id
`

type ListRecentSignaturesParams struct {
	Since     time.Time
	ExcludeID int64
}

type ListRecentSignaturesRow struct {
	ID      int64
	Minhash []int32
	EventID pgtype.Int8
}

// Wire stories are reprinted within hours, so only recent originals are compared.
func (q *Queries) ListRecentSignatures(ctx context.Context, arg ListRecentSignaturesParams) ([]ListRecentSignaturesRow, error) {
	rows, err := q.db.Query(ctx, listRecentSignatures, arg.Since, arg.ExcludeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentSignaturesRow{}
	for rows.Next() {
		var i ListRecentSignaturesRow
		if err := rows.Scan(&i.ID, &i.Minhash, &i.EventID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setArticleAnalysis = `-- name: SetArticleAnalysis :exec
UPDATE articles
SET development = $2, development_zh = $3, happened_on = $4, date_is_approximate = $5
WHERE id = $1
`

type SetArticleAnalysisParams struct {
	ID                int64
	Development       string
	DevelopmentZh     string
	HappenedOn        pgtype.Date
	DateIsApproximate bool
}

func (q *Queries) SetArticleAnalysis(ctx context.Context, arg SetArticleAnalysisParams) error {
	_, err := q.db.Exec(ctx, setArticleAnalysis,
		arg.ID,
		arg.Development,
		arg.DevelopmentZh,
		arg.HappenedOn,
		arg.DateIsApproximate,
	)
	return err
}

const setArticleImage = `-- name: SetArticleImage :exec
UPDATE articles SET image_url = $2 WHERE id = $1 AND image_url = ''
`

type SetArticleImageParams struct {
	ID       int64
	ImageUrl string
}

func (q *Queries) SetArticleImage(ctx context.Context, arg SetArticleImageParams) error {
	_, err := q.db.Exec(ctx, setArticleImage, arg.ID, arg.ImageUrl)
	return err
}

const setArticleLink = `-- name: SetArticleLink :exec
UPDATE articles
SET event_id = $2, step_article_id = $3, link_confidence = $4
WHERE id = $1
`

type SetArticleLinkParams struct {
	ID             int64
	EventID        pgtype.Int8
	StepArticleID  pgtype.Int8
	LinkConfidence pgtype.Float4
}

func (q *Queries) SetArticleLink(ctx context.Context, arg SetArticleLinkParams) error {
	_, err := q.db.Exec(ctx, setArticleLink,
		arg.ID,
		arg.EventID,
		arg.StepArticleID,
		arg.LinkConfidence,
	)
	return err
}

const setArticleReprint = `-- name: SetArticleReprint :exec
UPDATE articles
SET reprint_of_id = $2, event_id = $3
WHERE id = $1
`

type SetArticleReprintParams struct {
	ID          int64
	ReprintOfID pgtype.Int8
	EventID     pgtype.Int8
}

func (q *Queries) SetArticleReprint(ctx context.Context, arg SetArticleReprintParams) error {
	_, err := q.db.Exec(ctx, setArticleReprint, arg.ID, arg.ReprintOfID, arg.EventID)
	return err
}

const setArticleZh = `-- name: SetArticleZh :exec
UPDATE articles SET development_zh = COALESCE(NULLIF($1::text, ''), development_zh)
WHERE id = $2
`

type SetArticleZhParams struct {
	DevelopmentZh string
	ID            int64
}

// Fills the Traditional Chinese text of an analyzed article. An empty value
// keeps what is already stored, so a partial translation never erases text.
func (q *Queries) SetArticleZh(ctx context.Context, arg SetArticleZhParams) error {
	_, err := q.db.Exec(ctx, setArticleZh, arg.DevelopmentZh, arg.ID)
	return err
}

const setEntityAliases = `-- name: SetEntityAliases :exec
UPDATE entities SET aliases = $2, search_text = $3 WHERE id = $1
`

type SetEntityAliasesParams struct {
	ID         int64
	Aliases    []string
	SearchText string
}

func (q *Queries) SetEntityAliases(ctx context.Context, arg SetEntityAliasesParams) error {
	_, err := q.db.Exec(ctx, setEntityAliases, arg.ID, arg.Aliases, arg.SearchText)
	return err
}

const setEventSummary = `-- name: SetEventSummary :execrows
UPDATE events
SET summary = $1,
    summary_zh = '',
    summary_model = $2,
    summary_prompt_version = $3
WHERE id = $4 AND updated_at = $5
`

type SetEventSummaryParams struct {
	Summary           string
	Model             string
	PromptVersion     string
	ID                int64
	ExpectedUpdatedAt time.Time
}

// Do not let a slower job overwrite an overview made from newer coverage.
func (q *Queries) SetEventSummary(ctx context.Context, arg SetEventSummaryParams) (int64, error) {
	result, err := q.db.Exec(ctx, setEventSummary,
		arg.Summary,
		arg.Model,
		arg.PromptVersion,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setEventZh = `-- name: SetEventZh :exec
UPDATE events SET
    title_zh = COALESCE(NULLIF($1::text, ''), title_zh),
    summary_zh = COALESCE(NULLIF($2::text, ''), summary_zh)
WHERE id = $3
`

type SetEventZhParams struct {
	TitleZh   string
	SummaryZh string
	ID        int64
}

// Empty inputs preserve existing translations so title and summary can be
// backfilled independently.
func (q *Queries) SetEventZh(ctx context.Context, arg SetEventZhParams) error {
	_, err := q.db.Exec(ctx, setEventZh, arg.TitleZh, arg.SummaryZh, arg.ID)
	return err
}

const setReprintsEvent = `-- name: SetReprintsEvent :exec
UPDATE articles
SET event_id = $2
WHERE reprint_of_id = $1
`

type SetReprintsEventParams struct {
	ReprintOfID pgtype.Int8
	EventID     pgtype.Int8
}

// Reprints always live in their original's event.
func (q *Queries) SetReprintsEvent(ctx context.Context, arg SetReprintsEventParams) error {
	_, err := q.db.Exec(ctx, setReprintsEvent, arg.ReprintOfID, arg.EventID)
	return err
}

const setSummaryZh = `-- name: SetSummaryZh :exec
UPDATE summaries SET text_zh = $1 WHERE article_id = $2
`

type SetSummaryZhParams struct {
	TextZh    string
	ArticleID int64
}

func (q *Queries) SetSummaryZh(ctx context.Context, arg SetSummaryZhParams) error {
	_, err := q.db.Exec(ctx, setSummaryZh, arg.TextZh, arg.ArticleID)
	return err
}

const touchEvent = `-- name: TouchEvent :exec
UPDATE events
SET updated_at = GREATEST(updated_at, $1),
    timeline_text = $2,
    summary_prompt_version = ''
WHERE id = $3
`

type TouchEventParams struct {
	UpdatedAt    time.Time
	TimelineText string
	ID           int64
}

// Moves the event to the top of the homepage and refreshes its search text.
func (q *Queries) TouchEvent(ctx context.Context, arg TouchEventParams) error {
	_, err := q.db.Exec(ctx, touchEvent, arg.UpdatedAt, arg.TimelineText, arg.ID)
	return err
}
